#pragma once

#include "AtAscii.h"
#include "AtParse.h"


namespace At
{
	namespace Imf
	{
		// Add the id_AcceptObs flag to ParseTree to enable acceptance of obsolete forms.
		// RFC 5322 requires that new implementations do not use obsolete forms, but that implementations MUST accept obsolete encodings generated by other applications.

		DECL_RUID(AcceptObs)

		inline bool Is_std_qtext_char (uint c) { return (c == 33) || (c >= 35 && c <= 91) || (c >= 93 && c <= 126) || (c >= 128); }

		bool V_CR_nfb_LF  (ParseNode& p);
		bool V_field_name (ParseNode& p);

		DECL_RUID(ImfWs)

		DECL_RUID(FWS)
		DECL_RUID(std_dtext)
		DECL_RUID(obs_dtext_char)
		DECL_RUID(no_fold_literal)

		DECL_RUID(field_name)

		DECL_RUID(encw_start)
		DECL_RUID(encw_end)
		DECL_RUID(encw_charset)
		DECL_RUID(encw_encoding)
		DECL_RUID(encoded_text)
		DECL_RUID(encoded_word)
		DECL_RUID(encw_group)

		DECL_RUID(atext_word)
		DECL_RUID(dot_atom_text)
		DECL_RUID(phrase)
		DECL_RUID(phrase_list)

		DECL_RUID(utext_word)
		DECL_RUID(unstructured)

		DECL_RUID(quoted_pair)

		DECL_RUID(ctext_word)
		DECL_RUID(ccontent)
		DECL_RUID(comment)
		DECL_RUID(CFWS)

		DECL_RUID(qtext_word)
		DECL_RUID(qs_content)
		DECL_RUID(quoted_string)

		DECL_RUID(local_part)
		DECL_RUID(domain)
		DECL_RUID(addr_spec)

		DECL_RUID(angle_addr)
		DECL_RUID(obs_domain_list)
		DECL_RUID(name_addr)
		DECL_RUID(mailbox)

		DECL_RUID(mailbox_list)
		DECL_RUID(group)
		DECL_RUID(address)
		DECL_RUID(casual_addr_seps)
		DECL_RUID(address_list)

		DECL_RUID(2digits)
		DECL_RUID(4digits)

		DECL_RUID(day_name)
		DECL_RUID(day_digits)
		DECL_RUID(day)
		DECL_RUID(month)
		DECL_RUID(year_digits)
		DECL_RUID(year)
		DECL_RUID(date)
		DECL_RUID(zone)
		DECL_RUID(time)
		DECL_RUID(date_time)

		DECL_RUID(msg_id)

		DECL_RUID(kw_no)
		DECL_RUID(kw_auto_gen)
		DECL_RUID(kw_auto_repl)

		DECL_RUID(kw_return)
		DECL_RUID(kw_received)
		DECL_RUID(kw_resent_date)
		DECL_RUID(kw_resent_from)
		DECL_RUID(kw_resent_sender)
		DECL_RUID(kw_resent_to)
		DECL_RUID(kw_resent_cc)
		DECL_RUID(kw_resent_bcc)
		DECL_RUID(kw_resent_msg_id)
		DECL_RUID(kw_resent_rply)
		DECL_RUID(kw_date)
		DECL_RUID(kw_from)
		DECL_RUID(kw_sender)
		DECL_RUID(kw_reply_to)
		DECL_RUID(kw_to)
		DECL_RUID(kw_cc)
		DECL_RUID(kw_bcc)
		DECL_RUID(kw_message_id)
		DECL_RUID(kw_in_reply_to)
		DECL_RUID(kw_references)
		DECL_RUID(kw_subject)
		DECL_RUID(kw_comments)
		DECL_RUID(kw_keywords)
		DECL_RUID(kw_dkim_sig)
		DECL_RUID(kw_auto_sbmtd)

		DECL_RUID(path)
		DECL_RUID(return)
		DECL_RUID(received)
		DECL_RUID(obs_received)
		DECL_RUID(trace_fields)

		DECL_RUID(resent_date)
		DECL_RUID(resent_from)
		DECL_RUID(resent_sender)
		DECL_RUID(resent_to)
		DECL_RUID(resent_cc)
		DECL_RUID(resent_bcc)
		DECL_RUID(resent_msg_id)
		DECL_RUID(resent_rply)
		DECL_RUID(orig_date)

		DECL_RUID(from)
		DECL_RUID(sender)
		DECL_RUID(reply_to)
		DECL_RUID(to)
		DECL_RUID(cc)
		DECL_RUID(bcc)
		DECL_RUID(message_id)
		DECL_RUID(in_reply_to)
		DECL_RUID(references)
		DECL_RUID(subject)
		DECL_RUID(comments)
		DECL_RUID(keywords)

		DECL_RUID(dkim_hdr_list)
		DECL_RUID(dkim_auid)
		DECL_RUID(dkim_tag_name)
		DECL_RUID(dkim_tag_value)
		DECL_RUID(dkim_tag)
		DECL_RUID(dkim_tag_list)
		DECL_RUID(dkim_signature)

		DECL_RUID(auto_sbmtd_value)
		DECL_RUID(auto_sbmtd_field)

		DECL_RUID(opt_field_name)
		DECL_RUID(optional_field)
		DECL_RUID(inv_field_name)
		DECL_RUID(invalid_field)
		DECL_RUID(tr_resent_fields)
		DECL_RUID(main_fields)

		DECL_RUID(body)
		DECL_RUID(message_fields)
		DECL_RUID(message)

		bool C_ImfWs            (ParseNode& p);
		bool C_CFWS             (ParseNode& p);
		bool C_field_name       (ParseNode& p);
		bool C_phrase           (ParseNode& p);
		bool C_unstructured     (ParseNode& p);
		bool C_quoted_pair      (ParseNode& p);
		bool C_comment          (ParseNode& p);
		bool C_quoted_string    (ParseNode& p);
		bool C_local_part       (ParseNode& p);
		bool C_domain           (ParseNode& p);
		bool C_atext_word       (ParseNode& p);
		bool C_addr_spec        (ParseNode& p);
		bool C_angle_addr       (ParseNode& p);
		bool C_mailbox          (ParseNode& p);
		bool C_casual_addr_list (ParseNode& p);
		bool C_date_time        (ParseNode& p);
		bool C_msg_id_outer     (ParseNode& p);
		bool C_dkim_hdr_list    (ParseNode& p);
		bool C_dkim_auid        (ParseNode& p);
		bool C_dkim_signature   (ParseNode& p);
		bool C_trr_opt_inv_fld  (ParseNode& p);
		bool C_invalid_field    (ParseNode& p);
		bool C_any_field_noMime (ParseNode& p);
		bool C_message          (ParseNode& p);

	}
}
