#include "OgnIncludes.h"

#include "OgnConversions.h"


static_assert(OgnAutoSbmtd::Invalid				== (uint32_t) Imf::AutoSbmtdValue::Invalid,			"");
static_assert(OgnAutoSbmtd::No					== (uint32_t) Imf::AutoSbmtdValue::No,				"");
static_assert(OgnAutoSbmtd::AutoGenerated		== (uint32_t) Imf::AutoSbmtdValue::AutoGenerated,	"");
static_assert(OgnAutoSbmtd::AutoReplied			== (uint32_t) Imf::AutoSbmtdValue::AutoReplied,		"");

static_assert(OgnIpVerPref::None				== IpVerPreference::None,				"");
static_assert(OgnIpVerPref::Ip4					== IpVerPreference::Ip4,				"");
static_assert(OgnIpVerPref::Ip6					== IpVerPreference::Ip6,				"");

static_assert(OgnTlsAssurance::Unknown			== SmtpTlsAssurance::Unknown,			"");
static_assert(OgnTlsAssurance::NoTls			== SmtpTlsAssurance::NoTls,				"");
static_assert(OgnTlsAssurance::Tls_NoHostAuth	== SmtpTlsAssurance::Tls_NoHostAuth,	"");
static_assert(OgnTlsAssurance::Tls_AnyServer	== SmtpTlsAssurance::Tls_AnyServer,		"");
static_assert(OgnTlsAssurance::Tls_DomainMatch	== SmtpTlsAssurance::Tls_DomainMatch,	"");
static_assert(OgnTlsAssurance::Tls_ExactMatch	== SmtpTlsAssurance::Tls_ExactMatch,	"");

static_assert(OgnAuthType::None					== MailAuthType::None,					"");
static_assert(OgnAuthType::UseSuitable			== MailAuthType::UseSuitable,			"");
static_assert(OgnAuthType::AuthPlain			== MailAuthType::AuthPlain,				"");
static_assert(OgnAuthType::AuthCramMd5			== MailAuthType::AuthCramMd5,			"");

static_assert(OgnMsgStatus::NonFinal_Idle		== SmtpMsgStatus::NonFinal_Idle,		"");
static_assert(OgnMsgStatus::NonFinal_Sending	== SmtpMsgStatus::NonFinal_Sending,		"");
static_assert(OgnMsgStatus::Final_Sent			== SmtpMsgStatus::Final_Sent,			"");
static_assert(OgnMsgStatus::Final_Failed		== SmtpMsgStatus::Final_Failed,			"");
static_assert(OgnMsgStatus::Final_Aborted		== SmtpMsgStatus::Final_Aborted,		"");
static_assert(OgnMsgStatus::Final_GivenUp		== SmtpMsgStatus::Final_GivenUp,		"");

static_assert(OgnDeliveryState::None			== SmtpDeliveryState::None,				"");
static_assert(OgnDeliveryState::TempFailure		== SmtpDeliveryState::TempFailure,		"");
static_assert(OgnDeliveryState::PermFailure		== SmtpDeliveryState::PermFailure,		"");
static_assert(OgnDeliveryState::Success			== SmtpDeliveryState::Success,			"");

static_assert(OgnSendStage::None				== SmtpSendStage::None,					"");
static_assert(OgnSendStage::Unknown				== SmtpSendStage::Unknown,				"");
static_assert(OgnSendStage::RelayLookup			== SmtpSendStage::RelayLookup,			"");
static_assert(OgnSendStage::FindMx				== SmtpSendStage::FindMx,				"");
static_assert(OgnSendStage::Connect				== SmtpSendStage::Connect,				"");
static_assert(OgnSendStage::Greeting			== SmtpSendStage::Greeting,				"");
static_assert(OgnSendStage::Cmd_Ehlo			== SmtpSendStage::Cmd_Ehlo,				"");
static_assert(OgnSendStage::Capabilities		== SmtpSendStage::Capabilities,			"");
static_assert(OgnSendStage::Tls					== SmtpSendStage::Tls,					"");
static_assert(OgnSendStage::Cmd_Auth			== SmtpSendStage::Cmd_Auth,				"");
static_assert(OgnSendStage::Cmd_MailFrom		== SmtpSendStage::Cmd_MailFrom,			"");
static_assert(OgnSendStage::Cmd_RcptTo			== SmtpSendStage::Cmd_RcptTo,			"");
static_assert(OgnSendStage::Cmd_Data			== SmtpSendStage::Cmd_Data,				"");
static_assert(OgnSendStage::Content				== SmtpSendStage::Content,				"");
static_assert(OgnSendStage::Cmd_Quit			== SmtpSendStage::Cmd_Quit,				"");

static_assert(OgnSendErr::None									== SmtpSendErr::None,									"");
static_assert(OgnSendErr::Unknown								== SmtpSendErr::Unknown,								"");
static_assert(OgnSendErr::RelayLookup_LookupTimedOut			== SmtpSendErr::RelayLookup_LookupTimedOut,				"");
static_assert(OgnSendErr::RelayLookup_LookupError				== SmtpSendErr::RelayLookup_LookupError,				"");
static_assert(OgnSendErr::FindMx_LookupTimedOut					== SmtpSendErr::FindMx_LookupTimedOut,					"");
static_assert(OgnSendErr::FindMx_LookupError					== SmtpSendErr::FindMx_LookupError,						"");
static_assert(OgnSendErr::FindMx_LookupNoResults				== SmtpSendErr::FindMx_LookupNoResults,					"");
static_assert(OgnSendErr::FindMx_DomainMatchRequired			== SmtpSendErr::FindMx_DomainMatchRequired,				"");
static_assert(OgnSendErr::Connect_Error							== SmtpSendErr::Connect_Error,							"");
static_assert(OgnSendErr::Send_Error							== SmtpSendErr::Send_Error,								"");
static_assert(OgnSendErr::Reply_PrematureEndOfLine				== SmtpSendErr::Reply_PrematureEndOfLine,				"");
static_assert(OgnSendErr::Reply_UnrecognizedCodeFormat			== SmtpSendErr::Reply_UnrecognizedCodeFormat,			"");
static_assert(OgnSendErr::Reply_UnrecognizedLineSeparator		== SmtpSendErr::Reply_UnrecognizedLineSeparator,		"");
static_assert(OgnSendErr::Reply_InconsistentCode				== SmtpSendErr::Reply_InconsistentCode,					"");
static_assert(OgnSendErr::Reply_MaximumLengthExceeded			== SmtpSendErr::Reply_MaximumLengthExceeded,			"");
static_assert(OgnSendErr::Reply_ReceiveError					== SmtpSendErr::Reply_ReceiveError,						"");
static_assert(OgnSendErr::Greeting_SessionRefused				== SmtpSendErr::Greeting_SessionRefused,				"");
static_assert(OgnSendErr::Greeting_Unexpected					== SmtpSendErr::Greeting_Unexpected,					"");
static_assert(OgnSendErr::Ehlo_UnexpectedReply					== SmtpSendErr::Ehlo_UnexpectedReply,					"");
static_assert(OgnSendErr::Capabilities_8BitMimeRequired			== SmtpSendErr::Capabilities_8BitMimeRequired,			"");
static_assert(OgnSendErr::Capabilities_Size						== SmtpSendErr::Capabilities_Size,						"");
static_assert(OgnSendErr::Tls_NotAvailable						== SmtpSendErr::Tls_NotAvailable,						"");
static_assert(OgnSendErr::Tls_StartTlsRejected					== SmtpSendErr::Tls_StartTlsRejected,					"");
static_assert(OgnSendErr::Tls_SspiErr_LikelyDh_TooManyRestarts	== SmtpSendErr::Tls_SspiErr_LikelyDh_TooManyRestarts,	"");
static_assert(OgnSendErr::Tls_SspiErr_InvalidToken_IllegalMsg	== SmtpSendErr::Tls_SspiErr_InvalidToken_IllegalMsg,	"");
static_assert(OgnSendErr::Tls_SspiErr_ServerAuthRequired		== SmtpSendErr::Tls_SspiErr_ServerAuthRequired,			"");
static_assert(OgnSendErr::Tls_SspiErr_Other						== SmtpSendErr::Tls_SspiErr_Other,						"");
static_assert(OgnSendErr::Tls_CommunicationErr					== SmtpSendErr::Tls_CommunicationErr,					"");
static_assert(OgnSendErr::Tls_RequiredAssuranceNotAchieved		== SmtpSendErr::Tls_RequiredAssuranceNotAchieved,		"");
static_assert(OgnSendErr::Auth_AuthCommandNotSupported			== SmtpSendErr::Auth_AuthCommandNotSupported,			"");
static_assert(OgnSendErr::Auth_CfgAuthMechNotSupported			== SmtpSendErr::Auth_CfgAuthMechNotSupported,			"");
static_assert(OgnSendErr::Auth_NoSuitableAuthMechanism			== SmtpSendErr::Auth_NoSuitableAuthMechanism,			"");
static_assert(OgnSendErr::Auth_CfgAuthMechUnrecognized			== SmtpSendErr::Auth_CfgAuthMechUnrecognized,			"");
static_assert(OgnSendErr::Auth_Rejected							== SmtpSendErr::Auth_Rejected,							"");
static_assert(OgnSendErr::Auth_UnexpectedReply					== SmtpSendErr::Auth_UnexpectedReply,					"");
static_assert(OgnSendErr::Auth_UnexpectedCramMd5ChallengeReply	== SmtpSendErr::Auth_UnexpectedCramMd5ChallengeReply,	"");
static_assert(OgnSendErr::MailFrom_Rejected						== SmtpSendErr::MailFrom_Rejected,						"");
static_assert(OgnSendErr::MailFrom_UnexpectedReply				== SmtpSendErr::MailFrom_UnexpectedReply,				"");
static_assert(OgnSendErr::RcptTo_Rejected						== SmtpSendErr::RcptTo_Rejected,						"");
static_assert(OgnSendErr::RcptTo_UnexpectedReply				== SmtpSendErr::RcptTo_UnexpectedReply,					"");
static_assert(OgnSendErr::Data_Rejected							== SmtpSendErr::Data_Rejected,							"");
static_assert(OgnSendErr::Data_UnexpectedReply					== SmtpSendErr::Data_UnexpectedReply,					"");
static_assert(OgnSendErr::Content_Rejected						== SmtpSendErr::Content_Rejected,						"");
static_assert(OgnSendErr::Content_UnexpectedReply				== SmtpSendErr::Content_UnexpectedReply,				"");


namespace
{
	OgnResult OgnGetEnumValues(ValueDesc const* values, OgnEnumValues& x)
	{
		ORIGINATOR_FUNC_BEGIN
			x.m_storage = nullptr;
			x.m_nrValues = 0;
			x.m_values = nullptr;

			ValueDesc const* pValue = values;
			size_t count = 0;
			while (pValue->name != nullptr)
			{
				++count;
				++pValue;
			}

			x.m_storage = CoTaskMemAlloc(count * sizeof(OgnEnumValInfo));
			if (!x.m_storage)
				throw std::bad_alloc();

			OnExit freeStorage = [&] { CoTaskMemFree(x.m_storage); x.m_storage = nullptr; };
			OgnEnumValInfo* evi = (OgnEnumValInfo*) x.m_storage;
			size_t i = 0;

			while (values->name != nullptr)
			{
				EnsureThrow(i < count);
				evi[i].m_value = values->value;
				evi[i].m_name = values->name;
				evi[i].m_desc = values->desc;
				++i;
				++values;
			}

			x.m_nrValues = count;
			x.m_values = evi;

			freeStorage.Dismiss();
		ORIGINATOR_FUNC_CLOSE
	}
}	// anon


char const* __cdecl OgnIpVerPref_Name          (uint32_t v)                       { return IpVerPreference::Name(v); }
char const* __cdecl OgnIpVerPref_Desc          (uint32_t v)                       { return IpVerPreference::Desc(v); }
bool        __cdecl OgnIpVerPref_NameToVal     (OgnSeq n, OgnIpVerPref::E& v)     { return IpVerPreference::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnIpVerPref_Values        (OgnEnumValues& x)                 { return OgnGetEnumValues(IpVerPreference::sc_values, x); }

char const* __cdecl OgnTlsAssurance_Name       (uint32_t v)                       { return SmtpTlsAssurance::Name(v); }
char const* __cdecl OgnTlsAssurance_Desc       (uint32_t v)                       { return SmtpTlsAssurance::Desc(v); }
bool        __cdecl OgnTlsAssurance_NameToVal  (OgnSeq n, OgnTlsAssurance::E& v)  { return SmtpTlsAssurance::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnTlsAssurance_Values     (OgnEnumValues& x)                 { return OgnGetEnumValues(SmtpTlsAssurance::sc_values, x); }

char const* __cdecl OgnAuthType_Name           (uint32_t v)                       { return MailAuthType::Name(v); }
char const* __cdecl OgnAuthType_Desc           (uint32_t v)                       { return MailAuthType::Desc(v); }
bool        __cdecl OgnAuthType_NameToVal      (OgnSeq n, OgnAuthType::E& v)      { return MailAuthType::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnAuthType_Values         (OgnEnumValues& x)                 { return OgnGetEnumValues(MailAuthType::sc_values, x); }

char const* __cdecl OgnMsgStatus_Name          (uint32_t v)                       { return SmtpMsgStatus::Name(v); }
char const* __cdecl OgnMsgStatus_Desc          (uint32_t v)                       { return SmtpMsgStatus::Desc(v); }
bool        __cdecl OgnMsgStatus_NameToVal     (OgnSeq n, OgnMsgStatus::E& v)     { return SmtpMsgStatus::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnMsgStatus_Values        (OgnEnumValues& x)                 { return OgnGetEnumValues(SmtpMsgStatus::sc_values, x); }

char const* __cdecl OgnDeliveryState_Name      (uint32_t v)                       { return SmtpDeliveryState::Name(v); }
char const* __cdecl OgnDeliveryState_Desc      (uint32_t v)                       { return SmtpDeliveryState::Desc(v); }
bool        __cdecl OgnDeliveryState_NameToVal (OgnSeq n, OgnDeliveryState::E& v) { return SmtpDeliveryState::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnDeliveryState_Values    (OgnEnumValues& x)                 { return OgnGetEnumValues(SmtpDeliveryState::sc_values, x); }

char const* __cdecl OgnSendStage_Name          (uint32_t v)                       { return SmtpSendStage::Name(v); }
char const* __cdecl OgnSendStage_Desc          (uint32_t v)                       { return SmtpSendStage::Desc(v); }
bool        __cdecl OgnSendStage_NameToVal     (OgnSeq n, OgnSendStage::E& v)     { return SmtpSendStage::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnSendStage_Values        (OgnEnumValues& x)                 { return OgnGetEnumValues(SmtpSendStage::sc_values, x); }

char const* __cdecl OgnSendErr_Name            (uint32_t v)                       { return SmtpSendErr::Name(v); }
char const* __cdecl OgnSendErr_Desc            (uint32_t v)                       { return SmtpSendErr::Desc(v); }
bool        __cdecl OgnSendErr_NameToVal       (OgnSeq n, OgnSendErr::E& v)       { return SmtpSendErr::NameToValUInt(Seq_FromOgn(n), (uint32_t&) v); }
OgnResult   __cdecl OgnSendErr_Values          (OgnEnumValues& x)                 { return OgnGetEnumValues(SmtpSendErr::sc_values, x); }
